# theme.toml

name = "test theme"  # 替换为您的主题名称
description = "A Hugo theme with an AJAX-powered date timeline on the homepage."
version = "1.0.0"
license = "MIT"
min_version = "0.88.0"

[author]
  name = "Your Name"
  bio = "A brief bio about yourself."
  avatarurl = "images/your-avatar.jpg"

[params]
  # 主题自定义参数
  date_format = "2006-01-02"  # 日期格式
  timeline_color = "#007ACC"  # 时间轴的颜色，可以根据需要调整

[features]
  ajax = true  # 启用AJAX支持
  timeline = true  # 启用日期时间轴显示

[languages]
  [languages.en]
    title = "My Hugo Site"
    subtitle = "A modern Hugo theme with a date timeline"
    copyright = "© 2024 YourName"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2

  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 3

  [[menu.main]]
    name = "Donate"
    url = "/donate/"
    weight = 4

[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  taxonomyTerm = ["HTML", "RSS"]
  page = ["HTML"]
  sitemap = ["XML"]

[dependencies]
  [[dependencies.module]]
    path = "github.com/gohugoio/hugo-mod-jslibs"
    version = "v1.0.0"  # 示例模块版本

[taxonomies]
  category = "categories"
  tag = "tags"

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

buildFuture = true



  [params.vssue]
    enable = false
    vue_version = "runtime"  # runtime or full
    provider = "Github" # Github or Gitlab or Bitbucket or Gitee or Gitea
    owner = ""
    repo = ""
    clientId = ""
    clientSecret = ""
    basetest = "runtime"
  [params.gitalk]
    enable = false
    clientID = ""
    clientSecret = ""
    repo = ""
    owner = ""
    admin = ""
  [params.Waline]
    enable = false
    serverURL = ""
  [params.valine]
    enable = false
    appId = ""
    appKey = ""
  [params.giscus]
  enable = false
   src="https://giscus.app/client.js"
    data_repo="[在此输入仓库]"
    data_repo_id="[在此输入仓库 ID]"
    data_category="[在此输入分类名]"
    data_category_id="[在此输入分类 ID]"
    data_mapping="pathname"
    data_strict="0"
    data_reactions_enabled="1"
    data_emit_metadata="0"
    data_input_position="bottom"
    data_theme="preferred_color_scheme"
    data_lang="zh_CN"
    crossorigin="anonymous"